[package]
name = "relic-abi"
version = "0.0.1"
authors = ["Vinay Chandra Dommeti <relic@vinay.vc>"]
edition = "2018"
description = "Relic OS - ABI Package"

[dependencies]
static_assertions = "1.1.0"
