[workspace]
members = [
    "crates/supervisor/kernel",
    "crates/common/relic-abi",
    "crates/common/relic-std",
    "crates/common/relic-utils",
    "crates/userspace/relic-sigma",
]
default-members = []
