[package]
name = "relic-utils"
version = "0.0.1"
authors = ["Vinay Chandra Dommeti <relic@vinay.vc>"]
edition = "2018"
description = "Relic OS - Utilities Package"

[dependencies]
num = { version = "0.4", default-features = false }
